version: "3.1"
services:
  paste:
    container_name: pastebin
    image: daggy1234/pastebin
    restart: always
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - ./pastes:/usr/local/bin/pastes
      - ./static:/usr/local/bin/static
      - ./Rocket.toml:/usr/local/bin/Rocket.toml
  balancer:
    container_name: nginx
    image: nginx
    depends_on:
      - paste
    links:
      - paste
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs/:/etc/letsencrypt/
    expose:
      - 80
      - 443
    ports:
      - 80:80
      - 443:443
